-- Mentor and student profiles with explicit links to users
create table if not exists mentors_profiles (
    id uuid not null default gen_random_uuid(),
    user_id uuid not null,
    personal_info jsonb null default '{}'::jsonb,
    academic_info jsonb null default '{}'::jsonb,
    capacity integer null default 0,
    assigned_students integer null default 0,
    documents_verified boolean null default false,
    updated_at timestamptz null,
    remarks text null,
    verified_by uuid null,
    constraint mentors_profiles_pkey primary key (id),
    constraint mentors_profiles_user_id_key unique (user_id),
    constraint mentors_profiles_user_id_fkey foreign key (user_id) references users (id) on delete cascade,
    constraint mentors_profiles_verified_by_fkey foreign key (verified_by) references users (id)
);

create table if not exists students_profiles (
    id uuid not null default gen_random_uuid(),
    user_id uuid not null,
    mentor_id uuid null,
    personal_info jsonb null default '{}'::jsonb,
    academic_info jsonb null default '{}'::jsonb,
    documents_verified boolean null default false,
    updated_at timestamptz null,
    remarks text null,
    verified_by uuid null,
    gap_year boolean null default false,
    name text null,
    father_name text null,
    father_mobile text null,
    mother_name text null,
    mother_mobile text null,
    neet_roll_no text null,
    neet_rank integer null,
    neet_marks text null,
    application_no text null,
    dob date null,
    gender text null,
    neet_mobile text null,
    whatsapp_no text null,
    email text null,
    permanent_address jsonb null default '{}'::jsonb,
    correspondence_address jsonb null default '{}'::jsonb,
    bms_counselling_opted boolean null default false,
    bhs_counselling_opted boolean null default false,
    max_budget text null,
    minority boolean null default false,
    minority_type text null,
    nri_quota boolean null default false,
    special_quotas text[] null,
    domicile_state text null,
    single_child boolean null default false,
    stayed_in_state_since text null,
    tenth_school_details jsonb null default '{}'::jsonb,
    twelfth_school_details jsonb null default '{}'::jsonb,
    neet_category text null,
    constraint students_profiles_pkey primary key (id),
    constraint students_profiles_user_id_key unique (user_id),
    constraint students_profiles_user_id_fkey foreign key (user_id) references users (id) on delete cascade,
    constraint students_profiles_mentor_id_fkey foreign key (mentor_id) references mentors_profiles (id) on delete set null,
    constraint students_gender_check check (gender in ('male','female','other'))
);
